apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        # image: reddit-app:latest
        # imagePullPolicy: Never
        image: us-west2-docker.pkg.dev/mlops603-deploy/reddit-repo/reddit-app:fixed-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
